bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_extension = ".txt"
clip_skip = 2
dynamo_backend = "no"
enable_bucket = true
epoch = 20
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 8e-6
loss_type = "l2"
lr_scheduler = "cosine_with_restarts"
lr_scheduler_args = []
lr_scheduler_num_cycles = 3
lr_scheduler_power = 1
lr_warmup_steps = 30
max_bucket_reso = 2048
max_data_loader_n_workers = 12
max_grad_norm = 1
max_timestep = 1000
max_token_length = 150
max_train_steps = 150
mem_eff_attn = true
min_bucket_reso = 256
min_snr_gamma = 5
mixed_precision = "bf16"
network_alpha = 1
network_args = []
network_dim = 4
network_module = "networks.lora"
no_half_vae = true
noise_offset_type = "Original"
optimizer_args = [ "weight_decay=0.11", "betas=0.9,0.99",]
optimizer_type = "AdamW"
output_dir = "/pipeline/lora"
output_name = "test_of_the_name"
persistent_data_loader_workers = 1
pretrained_model_name_or_path = "/pipeline/checkpoint/animagine-xl-3.1.safetensors"
prior_loss_weight = 1
resolution = "1024,1536"
sample_prompts = "prompt.txt"
sample_sampler = "k_dpm_2_a"
save_model_as = "safetensors"
save_precision = "bf16"
text_encoder_lr = 0.0003
train_batch_size = 1
train_data_dir = "/pipeline/data"
unet_lr = 0.0003
xformers = true
